logging:
  level: INFO
  loggers:
    com.dropwizard: DEBUG

database:
  # the name of your JDBC driver
  driverClass: org.postgresql.Driver

  # the username
  user: pguser

  # the password
  password: user

  # the JDBC URL
  url: jdbc:postgresql://localhost:5432/library
